config/routes.rb
Rails.application.routes.draw do
  resources :karaoke_rooms do
	  resources :bookings
	end
  resque_web_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
    constraints resque_web_constraint do
    mount Resque::Server, :at => "/resque"
  end
  devise_for :users
  resources :songs, :artists, :karaoke_session, :plays, :favorites, :karaoke_rooms
  # get dashboard
  post "/enqueue" => "songs#enqueue"
  get "confirm_cue" => "songs#confirm_cue"
  post "confirm_cue" => "songs#confirm_cue"
  post "confirm_end_session" => "karaoke_session#confirm_end_session"
  get "confirm_favorite" => "favorites#confirm_favorite"
  post "confirm_favorite" => "favorites#confirm_favorite"  
#get 'home/index'
  root :to => "songs#index"
  post "skip" => "songs#skip"
  post "remove" => "songs#remove"
  post "play_pause" => "songs#play_pause"
  post "/karaoke_session/refresh_queued_songs/:id" => "karaoke_session#refresh_queued_songs"
  get "/karaoke_session/refresh_queued_songs/:id" => "karaoke_session#refresh_queued_songs"
  get "/request_passkey" => "songs#request_passkey"
  post "/submit_passkey" => "songs#submit_passkey"
  get "capitol_hits" => "plays#top_plays"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :admins
  

end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
  end

  def create
    song_id = Song.find_by(soID: params[:song]).id
    if current_user.favorites.any? {|f| f.song_id == song_id}
        redirect_back( fallback_location: (request.referer || root_path), notice: "this song is already in your favorites")
    else
      favorite = Favorite.new
      favorite.song_id = Song.find_by(soID: params[:song]).id
      favorite.user_id = current_user.id
      # play.karaoke_session_id = 
      favorite.save
        redirect_back( fallback_location: (request.referer || root_path), notice: "song has been added to your favorites")
    end    
  end

  def confirm_favorite
      @song = Song.find(params[:song])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    favorite = Favorite.find(params[:id])
    favorite.destroy
      redirect_to favorites_path, :notice => "favorite has been deleted"
  end

end

app/views/favorites/_confirm_favorite.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title" id="myModalLabel">Add <%= @song.title %> to your Favorites?</h4>
</div>
<div class="modal-body">

  <%= form_tag("/favorites", method: "post") do %>
    <%= hidden_field_tag(:song, @song.soID) %>
    <%= submit_tag("Confirm", :class => "btn btn-primary btn-small") %>
  <% end %>

</div>
<div class="modal-footer">
<i>Now that is karaoke&trade;</i>
</div>

app/views/favorites/confirm_favorite.js.erb
$("#confirm_cue_modal").html("<%= escape_javascript(render 'favorites/confirm_favorite') %>");

app/views/favorites/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  <table class = "table table-striped">
    <thead>
      <tr>
        <th>click queue to add a song!</th>
        <th></th>
        <!-- <th>Category</th> -->
      </tr>
  </thead>
  </head>
  <body>
   <tbody>
    <% if @favorites.empty?%>
      <tr><td>
       <p>add a song to your favorites search results to sing later!</p>
      </tr></td>

      <% else %>
        <% @favorites.each do |favorite| %>
          <tr>
            <td>
            <dl><% song = Song.find favorite.song_id %><%=song.title %>
              <br/>


              <%= link_to song.artist.name, artist_path(song.artist.id) %>
              <br/>
<!--             <%= text_area_tag( size: "23x2") %> -->
<!--             <form name="myform">
             <input type="text" />
             <button class="buttonFinish"></button>
            </form>
 -->
            <script type="javascipt">
            // $(document).ready(function() {
            //     $('.buttonFinish').click(function(){
            //         $('.myform').submit();
            //     });
            // }
            </script>

              <!-- artist_path = show artists_path = index -->
            </td>

            <td>

          <% if user_signed_in? == true %>
            <% unless song.soID == nil %>
            <%= button_to 'Cue', confirm_cue_path(:song => song.id),  {:remote => true, 'data-toggle' =>  "modal", :class => 'btn btn-primary btn-small', 'data-target' => '#myModal'}  %>
            <% end %>
          <% else %>
            <%= button_to 'Cue', new_user_session_path %>
            <% end %>
            </td><td>

          <%= button_to 'Delete', favorite_path(favorite.id), :method => :delete, :class => 'btn btn-default btn-small' %>


          <% end %> 
      <% end %>
       <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-sm" role="document">
            <div id="confirm_cue_modal" class="modal-content">
              
            </div>
          </div>
        </div>

  </tbody>
  </body>
</html>