config/routes.rb
Rails.application.routes.draw do
  resources :karaoke_rooms do
	  resources :bookings
	end
  resque_web_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
    constraints resque_web_constraint do
    mount Resque::Server, :at => "/resque"
  end
  devise_for :users
  resources :songs, :artists, :karaoke_session, :plays, :favorites, :karaoke_rooms
  # get dashboard
  post "/enqueue" => "songs#enqueue"
  get "confirm_cue" => "songs#confirm_cue"
  post "confirm_cue" => "songs#confirm_cue"
  post "confirm_end_session" => "karaoke_session#confirm_end_session"
  get "confirm_favorite" => "favorites#confirm_favorite"
  post "confirm_favorite" => "favorites#confirm_favorite"  
#get 'home/index'
  root :to => "songs#index"
  post "skip" => "songs#skip"
  post "remove" => "songs#remove"
  post "play_pause" => "songs#play_pause"
  post "/karaoke_session/refresh_queued_songs/:id" => "karaoke_session#refresh_queued_songs"
  get "/karaoke_session/refresh_queued_songs/:id" => "karaoke_session#refresh_queued_songs"
  get "/request_passkey" => "songs#request_passkey"
  post "/submit_passkey" => "songs#submit_passkey"
  get "capitol_hits" => "plays#top_plays"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :admins
  

end

app/models/karaoke_room.rb
class KaraokeRoom < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :bookings
  has_many :karaoke_sessions
end

app/controllers/karaoke_rooms_controller.rb
class KaraokeRoomsController < ApplicationController

  def index
    @karaoke_rooms = KaraokeRoom.all
  end

  def new
    @karaoke_room = KaraokeRoom.new
  end

  #post karaoke_room/:id
  def show
    @singers = KaraokeRoom.find_by(name: params[:id]).singers
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @singers }
    end
  end

  # def create
  #   @karaoke_room = KaraokeRoom.create(karaoke_room_params)
  #   if @karaoke_room.save
  #     name = @karaoke_room.name
  #     redirect_to karaoke_rooms_path
  #     flash[:notice] = "#{name} created"
  #   else
  #     render 'new'
  #     flash[:error] = "Unable to create karaoke room. Please try again"
  #   end
  # end

  # def destroy
  #   @karaoke_room = KaraokeRoom.find(params[:id])
  #   @karaoke_room.destroy
  #   redirect_to karaoke_rooms_path
  # end

  # def edit
  #   @karaoke_room = KaraokeRoom.find(params[:id])
  # end

  # def update
  #   @karaoke_room = KaraokeRoom.find(params[:id])
  #   @karaoke_room.update karaoke_room_params
  #   if @karaoke_room.save
  #     flash[:notice] = "Your karaoke room was updated succesfully"
  #     redirect_to root_path
  #   else
  #     render 'edit'
  #   end
  # end

  private

    def karaoke_room_params
      params.require(:karaoke_room).permit(:name, :delete)
    end

end

app/views/karaoke_rooms/_errors.html.erb
<% if @karaoke_room.errors.any? %>
  <div class="errors">
    <h3>
      <%= pluralize(@karaoke_room.errors.count, 'error') %>
      prohibited this karaoke_room from being saved:
    </h3>
    <ul>
      <% @karaoke_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/karaoke_rooms/_form.html.erb
<%= form_for @karaoke_room do |f| %>
  <%= render 'errors' %>
  <%= f.label 'name', 'Name' %>
  <%= f.text_field 'name', placeholder: 'Name'%>
  <%= f.submit 'Submit' %>
<% end %>

app/views/karaoke_rooms/edit.html.erb
<%= render 'form' %>

app/views/karaoke_rooms/index.html.erb
<h3>karaoke rooms</h3>

<% @karaoke_rooms.each do |karaoke_room| %>
  <div class="karaoke_room">
    <%= karaoke_room.name %>
    <%= link_to "Show all bookings", karaoke_room_bookings_path(karaoke_room) %>
    <%= link_to "Delete", karaoke_room_path(karaoke_room), data: { confirm: 'Are you sure?' }, method: :delete %>
    <%= link_to "Edit", edit_karaoke_room_path(karaoke_room) %>
    <%= link_to "Add booking", new_karaoke_room_booking_path(karaoke_room) %>
  </div>
<% end %>

app/views/karaoke_rooms/new.html.erb
<%= render 'form' %>