config/routes.rb
Rails.application.routes.draw do
  resources :karaoke_rooms do
	  resources :bookings
	end
  resque_web_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
    constraints resque_web_constraint do
    mount Resque::Server, :at => "/resque"
  end
  devise_for :users
  resources :songs, :artists, :karaoke_session, :plays, :favorites, :karaoke_rooms
  # get dashboard
  post "/enqueue" => "songs#enqueue"
  get "confirm_cue" => "songs#confirm_cue"
  post "confirm_cue" => "songs#confirm_cue"
  post "confirm_end_session" => "karaoke_session#confirm_end_session"
  get "confirm_favorite" => "favorites#confirm_favorite"
  post "confirm_favorite" => "favorites#confirm_favorite"  
#get 'home/index'
  root :to => "songs#index"
  post "skip" => "songs#skip"
  post "remove" => "songs#remove"
  post "play_pause" => "songs#play_pause"
  post "/karaoke_session/refresh_queued_songs/:id" => "karaoke_session#refresh_queued_songs"
  get "/karaoke_session/refresh_queued_songs/:id" => "karaoke_session#refresh_queued_songs"
  get "/request_passkey" => "songs#request_passkey"
  post "/submit_passkey" => "songs#submit_passkey"
  get "capitol_hits" => "plays#top_plays"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :admins
  

end

app/models/booking.rb
require 'active_support/concern'

class Booking < ActiveRecord::Base
  include Bookable
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  respond_to :html, :xml, :json
  
  before_action :find_karaoke_room

  def index
    @bookings = Booking.where("karaoke_room_id = ? AND end_time >= ?", @karaoke_room.id, Time.now).order(:start_time)
    respond_with @bookings
  end

  def new
    @booking = Booking.new(karaoke_room_id: @karaoke_room.id)
  end

  def create
    @booking =  Booking.new(params[:booking].permit(:karaoke_room_id, :start_time, :length))
    @booking.karaoke_room = @karaoke_room
    if @booking.save
      redirect_to karaoke_room_bookings_path(@karaoke_room, method: :get)
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id]).destroy
    if @booking.destroy
      flash[:notice] = "Booking: #{@booking.start_time.strftime('%e %b %Y %H:%M%p')} to #{@booking.end_time.strftime('%e %b %Y %H:%M%p')} deleted"
      redirect_to karaoke_room_bookings_path(@karaoke_room)
    else
      render 'index'
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    # @booking.karaoke_room = @karaoke_room

    if @booking.update(params[:booking].permit(:karaoke_room_id, :start_time, :length))
      flash[:notice] = 'Your booking was updated succesfully'

      if request.xhr?
        render json: {status: :success}.to_json
      else
        redirect_to karaoke_room_bookings_path(@karaoke_room)
      end
    else
      render 'edit'
    end
  end

  private

  def save booking
    if @booking.save
        flash[:notice] = 'booking added'
        redirect_to karaoke_room_booking_path(@karaoke_room, @booking)
      else
        render 'new'
      end
  end

  def find_karaoke_room
    if params[:karaoke_room_id]
      @karaoke_room = KaraokeRoom.find_by_id(params[:karaoke_room_id])
    end
  end

end

app/views/bookings/_errors.html.erb
<% if @booking.errors.any? %>
  <div class="errors">
    <h3><%= pluralize(@booking.errors.count, 'error') %>
      prohibited this booking from being saved:
    </h3>
    <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<%= form_for([@karaoke_room, @booking]) do |f| %>
  <p>
    <%= f.label 'start_time', 'Start time' %>
    <%= f.datetime_select :start_time, { minute_step: 15 } %>
  </p>
  <p>
    <%= f.label 'length', 'Length of booking in hours' %>
    <%= f.number_field 'length', min: 1 %>
  </p>
  <%= f.submit 'Submit' %>
<% end %> 

app/views/bookings/edit.html.erb
<h3>Edit booking for <%= @karaoke_room.name %></h3>

<%= render 'errors' %>
<%= render 'form' %>

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/bookings/index.html.erb
<h3> Bookings for <%= @karaoke_room.name %></h3>
<table class="bookings_table">
  <tr>
    <th>Start</th>
    <th>End</th>
  </tr>
  
  <% @bookings.each do |booking| %>
  <tr>
    <td>
      <%= booking.start_time.strftime('%e %b %Y %H:%M%p') %>
    </td>
    <td>
      <%= (booking.calculate_end_time + 60).strftime('%e %b %Y %H:%M%p') %>
    </td>
    <td><%= link_to "Delete", karaoke_room_booking_path(@karaoke_room, booking), data: { confirm: 'Are you sure?' }, method: :delete %>
    </td>
    <td><%= link_to "Edit", edit_karaoke_room_booking_path(@karaoke_room, booking) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/bookings/new.html.erb
<h3>Add booking for <%= @karaoke_room.name %></h3>
  
<%= render 'errors' %>
<%= render 'form' %> 

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/bookings/show.html.erb
<h3>Booking Confirmation</h3>
<p>Your booking is confirmed for
  <%= @karaoke_room.name %>:
  <%= @booking.start_time.strftime('%e %b %Y %H:%M%p') %>
  until
  <%= (@booking.calculate_end_time + 60).strftime('%e %b %Y %H:%M%p') %>