config/routes.rb
Rails.application.routes.draw do
  resources :karaoke_rooms do
	  resources :bookings
	end
  resque_web_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
    constraints resque_web_constraint do
    mount Resque::Server, :at => "/resque"
  end
  devise_for :users
  resources :songs, :artists, :karaoke_session, :plays, :favorites, :karaoke_rooms
  # get dashboard
  post "/enqueue" => "songs#enqueue"
  get "confirm_cue" => "songs#confirm_cue"
  post "confirm_cue" => "songs#confirm_cue"
  post "confirm_end_session" => "karaoke_session#confirm_end_session"
  get "confirm_favorite" => "favorites#confirm_favorite"
  post "confirm_favorite" => "favorites#confirm_favorite"  
#get 'home/index'
  root :to => "songs#index"
  post "skip" => "songs#skip"
  post "remove" => "songs#remove"
  post "play_pause" => "songs#play_pause"
  post "/karaoke_session/refresh_queued_songs/:id" => "karaoke_session#refresh_queued_songs"
  get "/karaoke_session/refresh_queued_songs/:id" => "karaoke_session#refresh_queued_songs"
  get "/request_passkey" => "songs#request_passkey"
  post "/submit_passkey" => "songs#submit_passkey"
  get "capitol_hits" => "plays#top_plays"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :admins
  

end

app/models/song.rb
class Song < ApplicationRecord
  has_many :plays
  has_many :users, through: :plays

  has_many :favorites
  has_many :users, through: :favorites

  include PgSearch
  multisearchable :against => :title,
                    :using => {
                    :tsearch => {:dictionary => "english"}
                  }

  belongs_to :artist

  @@api_token = Rails.application.secrets.onsite_api_key
  @@kjams_database = "http://#{$kjams_api}/"
  def self.import_all_songs
    songs_exist = Song.all.collect{ |e| e[:soID]}
    response = HTTParty.post("#{@@kjams_database}get_all_songs", headers: {"Authorization" => "Token token=#{@@api_token}"})
    response.each do |e|
      if ((songs_exist.include? e["soID"]) == false)
        song = Song.new 
        song.soID = e["soID"]
        # song.artist_id = e["arts"]
        song.title = e["name"]
        if Artist.where({name: e["arts"]}).empty?
          artist = Artist.new
          artist.name = e["arts"]
          artist.save
          song.artist_id = artist.id
        else
          song.artist_id = Artist.find_by({name: e["arts"]}).id
        end
        song.save
     end
   end
  end


  def self.search(search)
    songs = []
    results = PgSearch.multisearch(search)
    results.each do |result|
      if result.searchable_type == "Artist"
        songs << Artist.find(result.searchable_id).songs
      else result.searchable_type == "Song"
        songs << Song.find(result.searchable_id)
      end
    end
    songs.flatten!
    return songs
  end

  def self.rankSongsByPlays #this logic should maybe change to Song.all once the plays table is bigger than the songs table?
    #Better approach ideas:
  # 13:21 <@xnor> maybe something in here? http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html
  # 13:27 <@xnor> AR might be able to do it directly, Play.calculate(:count, :song_id).order(:count).limit(100) ?
  # 13:28 <@xnor> Play.calculate(:count, :song_id).order(:count).limit(100).pluck(:song_id).. something like that
    ranked_plays = [] #[{song_id: foo, play_count: bar}, etc]
    top_songs = []
    Play.all.each do |p|
      if ranked_plays.any? {|h| h[:song_id] == p.song_id} 
        song = ranked_plays.find {|h| h[:song_id] == p.song_id}
        song[:play_count] += 1 
      else
        ranked_plays << {song_id: p.song_id, play_count: 1}
      end 
    end
    ranked_plays.sort! {|x,y| y[:play_count] <=> x[:play_count]}
    ranked_plays[0,99].each do |s|
      song = Song.find s[:song_id]
      top_songs << song
    end
    return top_songs
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :require_active_karaoke_session, only: [:confirm_cue, :enqueue, :skip, :remove, :play_pause]
  # before_action :set_song, only: [:show, :edit, :update, :destroy]

  @@kjams_database = "http://#{$kjams_api}"
  @@api_token = Rails.application.secrets.onsite_api_key
  # GET /songs
  # GET /songs.json
  # def index
  #   @songs = Song.all
  # end
  def index
    @songs = Song.search(params[:search])
  end


  #   @songs = Song.search(params[:search])
  # end

  # def artist_search
  #   @songs = Song.artist_search(song.artist)
  # end

  def confirm_cue
    @song = Song.find(params[:song])
    @singers = []
    karaoke_session = KaraokeSession.find session[:karaoke_session]
    room = KaraokeRoom.find karaoke_session.karaoke_room_id
    Rails.logger.debug "!!!!!!!!!!working with room number #{room.name}"
    room.singers.each do |e|
      unless (e["name"].empty? && e["siID"].empty?) 
        @singers << OpenStruct.new(:name => e["name"], :siID => e["siID"])
      end
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def request_passkey
  end

  def submit_passkey
    party = {}
    passkey_downcased = params[:passkey].downcase
    parties = KaraokeSession.where(token: passkey_downcased)
    parties.each do |p| 
      if p.is_active == "true"
        party = p
      end
    end
    if party.present?
      session[:karaoke_session] = party.id
      set_karaoke_session_cookie passkey_downcased
    else
      redirect_back( fallback_location: (request.referer || root_path), notice: "Sorry wrong passkey!")
    end
  end

  def enqueue
    puts "gonna enqueue song #{params[:song]}"
    if params[:'singer-dropdown'].present?
      singer_name = params[:'singer-dropdown']
    else 
      singer_name = params[:singer]
    end
    karaoke_session = KaraokeSession.find session[:karaoke_session]
    room = KaraokeRoom.find karaoke_session.karaoke_room_id
    Resque.enqueue(CueSong, *[room.name, singer_name, params[:song]])
    play = Play.new
    play.song_id = Song.find_by(soID: params[:song]).id
    play.user_id = current_user.id
    # play.karaoke_session_id = 
    play.save
    redirect_to "/karaoke_session/0", notice: "Song enqueued!"
  end

  # def skip
  #   puts "gonna skip a track!"
  #   response = HTTParty.post("#{@@kjams_database}/skip", query: {room: 0}, headers: {"Authorization" => "Token token=#{@@api_token}"})
  #   redirect_to "/karaoke_session/0", notice: "track skipped!!"
  # end

  # def remove
  #   puts "gonna remove a track!"
  #   response = HTTParty.post("#{@@kjams_database}/remove_current_song", query: {room: 0}, headers: {"Authorization" => "Token token=#{@@api_token}"})
  #   redirect_to "/karaoke_session/0", notice: "track removed!!"
  # end

  # def play_pause
  #   puts "changing play/pause state!"
  #   response = HTTParty.post("#{@@kjams_database}/play_pause", query: {room: 0}, headers: {"Authorization" => "Token token=#{@@api_token}"})
  #   redirect_to "/karaoke_session/0", notice: "changed play/pause!!"
  # end
    

  # # GET /songs/1
  # # GET /songs/1.json
  # def show
  # end

  # # GET /songs/new
  # def new
  #   @song = Song.new
  # end

  # GET /songs/1/edit
  # def edit
  # end

  # POST /songs
  # POST /songs.json
  # def create
  #   @song = Song.new(song_params)

  #   respond_to do |format|
  #     if @song.save
  #       format.html { redirect_to @song, notice: 'Song was successfully created.' }
  #       format.json { render :show, status: :created, location: @song }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @song.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /songs/1
  # # PATCH/PUT /songs/1.json
  # def update
  #   respond_to do |format|
  #     if @song.update(song_params)
  #       format.html { redirect_to @song, notice: 'Song was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @song }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @song.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /songs/1
  # # DELETE /songs/1.json
  # def destroy
  #   @song.destroy
  #   respond_to do |format|
  #     format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
  # Use callbacks to share common setup or constraints between actions.
  def require_active_karaoke_session
    unless active_karaoke_session_check
      flash[:error] = "Sorry - not an active passkey!"
      if params[:song].present?
        session[:interrupted_songcue] = params[:song]
        redirect_to "/request_passkey"# halts request cycle
      else
      redirect_to "/request_passkey"# halts request cycle
      end
    end
  end

  def set_karaoke_session_cookie(passkey)
    if KaraokeSession.where(:token=>passkey).where(:is_active=>"true").first.present?
      karaoke_session = KaraokeSession.where(:token=>passkey).where(:is_active=>"true").first
      session[:karaoke_session] = karaoke_session.id
      if session[:interrupted_songcue].present?
        song = Song.find session[:interrupted_songcue]
        room = KaraokeRoom.find karaoke_session.karaoke_room_id
        Resque.enqueue(CueSong, *[room.name, current_user.username, song.soID])
        play = Play.new
        play.song_id = song.id
        play.user_id = current_user.id
        # play.karaoke_session_id = 
        play.save
        redirect_to "/karaoke_session/0", notice: "Song enqueued!"
      else
        redirect_to root_path, notice: "Welcome to the party!"
      end
    else
      redirect_to "/request_passkey"
    end
  end

  def active_karaoke_session_check
    if session[:karaoke_session].present?
      party = KaraokeSession.find session[:karaoke_session]
      if party.is_active == "true"
        if party.end_time > Time.now
          return true #party is going strong
        else
          set_party_to_limbo party
          return false #party is out of time and paused + set to limbo
        end
      else
        return false #party is already flagged as inactive or limbo
      end
    else
      return false #user doesn't have a karaoke_session in their cookie
    end
  end

  def set_party_to_limbo(party) #TODO CHANGE PLAYPAUSE TO AN EXPLICIT PAUSE check state of song (if playing wait till end)
    room = KaraokeRoom.find party.karaoke_room_id
    party.is_active = "limbo"
    party.save
    HTTParty.post("#{@@kjams_database}/play_pause", query: {room: room.name}, headers: {"Authorization" => "Token token=#{@@api_token}"})
  end

  # def set_song
  #   @song = Song.find(params[:id])
  # end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  # def song_params
  #   params.require(:song).permit(:title, :artist, :location, :category)
    
  # end

    # def play_pause
    #   HTTParty.post("#{@@server_url}/play_pause", query: {room: params[:room], token: params[:token]})
    # end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_confirm_cue.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title" id="myModalLabel">Add <%= @song.title %> to your cue?</h4>
</div>
<div class="modal-body">
  <%= form_tag("/enqueue", method: "post") do %>
    <%if current_user.username == "room_console"%>
      <%= label_tag(:singer, "Enter your screen name") %>
      <%= text_field_tag(:singer) %>
      <br />
      Or select from below:
      <%= select_tag "singer-dropdown", options_from_collection_for_select(@singers, "name", "name") %>
    <%else%>
      <%= hidden_field_tag(:singer, current_user.username) %>
    <%end%>
    <%= hidden_field_tag(:room, 0) %>
    <%= hidden_field_tag(:song, @song.soID) %>
    <br />
    <%= submit_tag("Confirm", :class => "btn btn-primary btn-small") %>
  <% end %>
</div>
<div class="modal-footer">
<i>Now that is karaoke&trade;</i>
</div>

app/views/songs/_form.html.erb
<%= form_for(song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_navigation.html.erb
<!DOCTYPE html>
<html>
	<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script>
      $(document).ready(function(){
          $("#search").keyup(function(){
              $("#searchclear").toggle(Boolean($(this).val()));
          });
          $("#searchclear").toggle(Boolean($("#search").val()));
          $("#searchclear").click(function(){
              $("#search").val('').focus();
              $(this).hide();
          });
      });
    </script>


  </head>
	<body>
    <nav class="navbar navbar-trans navbar-default navbar-fixed-top" role="navigation" id="topnavbar">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#songs-navbar-collapse-1" aria-expanded="false">

            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

          </button>

            <div class="navbar-search navbar-left">
              <span>
                <div class="search-field">
                <%= form_tag songs_path, :method => 'get' do %>
                  <div class="btn-group">
                    <%= text_field_tag(:search, params[:search], class: "search-text-field") %>
                    <span id="searchclear" class="glyphicon glyphicon-remove-circle"></span>
                  </div>
                    <%= button_tag(type: 'submit', class: "btn btn-primary btn-small") do %>
                      <span class="glyphicon glyphicon-search"></span>
                    <% end %>
                  </div>
                <% end %>
              </span>
            </div>
          </div>
             
        <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="songs-navbar-collapse-1">
    <ul class="nav navbar-nav" data-hook="top-header-navbar">

      <a class="navbar-brand" href="/songs#index">
        <span></span>
      </a>

      <li >
        <% if user_signed_in? %>
        <!-- TODO: populate the following with link_to helper linked to users session.-->
          <a href="/karaoke_session/0">Cue</a>
        <% end %>
      </li>
      <li  >
        <a href="/artists">Artists</a>
      </li>
      <li >
        <% if user_signed_in? %>
         <a href="/plays">History</a>
      </li>
      <li >
         <a href="/favorites">Faves</a>
        <% end %>
      </li>
      <li >
        <a href="/capitol_hits">Capitol Hits</a>
      </li>
      <li >
        <% if user_signed_in? %>
          <% if current_user.admin?%>
            <a href="/karaoke_session">Dashboard</a>
          <% end %>
        <% end %>
      </li>
<!--       <li  > where search used to live.

      </li> -->
    </ul>
    <ul class="navbar-text navbar-nav navbar-right">
      <li id="devise">
        <% if user_signed_in? %>
          <strong><%= current_user.username %></strong> 
          <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </li>
    </ul>
    </div>
  </div>
    <!-- /.navbar-collapse -->
  </div>
    <!-- /.container-fluid -->
  </nav>
	</body>
</html>

app/views/songs/confirm_cue.js.erb
$("#confirm_cue_modal").html("<%= escape_javascript(render 'songs/confirm_cue') %>");
$( "#singer-dropdown" ).select2({
  placeholder: 'choose or type name',
  allowClear: true,

});
$('#singer-dropdown').val('').trigger('change')

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>list of songs</title>
    <p id="notice"><%= notice %></p>

  <table class = "table table-striped">
      <thead>
        <tr>
          <th>click cue to add a song!</th>
          <th></th>
          <!-- <th>Category</th> -->
        </tr>
      </thead>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <tbody>
      <% if @songs == ["nothing"]%>
      <tr><td>
       <p> enter a song or artist into the search!</p>
      </tr></td>

      <% else %>
        <% @songs.each do |song| %>
          <tr>
            <td>
            <dl><%= song.title %><br/>


              <%= link_to song.artist.name, artist_path(song.artist.id) %>

              <!-- artist_path = show artists_path = index -->


            </td>

            <td>
          <% if user_signed_in? == true %>
            <% unless song.soID == nil %>
            <%= button_to 'Cue', confirm_cue_path(:song => song.id),  {:remote => true, 'data-toggle' =>  "modal", :class => 'btn btn-primary btn-small', 'data-target' => '#myModal'}  %>
            <% end %>
          <% else %>
            <%= button_to 'Cue', new_user_session_path(:song => song.id) %>
            <% end %>
          </td>

          <td>
          <% if user_signed_in? == true %>
            <% unless song.soID == nil %>
            <%= button_to '<3', confirm_favorite_path(:song => song.id),  {:remote => true, 'data-toggle' =>  "modal", :class => 'btn btn-default btn-small', 'data-target' => '#myModal'}   %>
            <% end %>
          <% else %>
            <% end %>


          <% end %> 
      <% end %>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-sm" role="document">
            <div id="confirm_cue_modal" class="modal-content">
              
            </div>
          </div>
        </div>
        </dl></td> 

        </tr>
    </tbody>
  </table>
  </body>
</html>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/request_passkey.html.erb
<html lang="en">
  <head>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title></title>
    <p id="notice"><%= notice %></p>

  <table class = "table table-striped">
      <thead>
        <tr>
          <th>click cue to add a song!</th>
          <th></th>
          <!-- <th>Category</th> -->
        </tr>
      </thead>
  </table>
  <script>
  $( document ).ready(function() {
    $('#myModal').modal('show')
  });
  </script>
  </head>
  <body>

      <!-- request passkey modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
      <div id="request_new_passkey" class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Join a party</h4>
        </div>
        <div class="modal-body">
          <%= form_tag("/submit_passkey", method: "post") do %>
            <%= label_tag(:passkey, "Enter your passphrase") %>
            <%= text_field_tag(:passkey) %>
            <br />
            <%= submit_tag("Submit", :class => "btn btn-primary btn-small") %>
          <% end %>
        </div>
        <div class="modal-footer">
        <i>Now that is karaoke&trade;</i>
        </div>

      </div>
    </div>
  </div>
  </body>
  </html>

app/views/songs/show.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>

    <p>
      <strong>Title:</strong>
      <%= @song.title %>
    </p>

    <p>
      <strong>Artist:</strong>
      <%= @song.artist %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @song.location %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @song.category %>
    </p>

  <%= link_to 'Edit', edit_song_path(@song) %> |
  <%= link_to 'Back', songs_path %>
</body>
</html>